name: auth_buttons
description: Auth Buttons is a flutter widget library, include buttons for authenticating with the most popular social networks like Google, Facebook, Apple and Twitter.
version: 2.0.2
homepage: https://github.com/elbeicktalat/flutter_auth_buttons

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - packages/auth_buttons/images/default/apple.svg
    - packages/auth_buttons/images/default/apple_white.svg
    - packages/auth_buttons/images/default/email.svg
    - packages/auth_buttons/images/default/email_white.svg
    - packages/auth_buttons/images/default/facebook.svg
    - packages/auth_buttons/images/default/facebook_white.svg
    - packages/auth_buttons/images/default/github_black.svg
    - packages/auth_buttons/images/default/github_white.svg
    - packages/auth_buttons/images/default/google.svg
    - packages/auth_buttons/images/default/huawei.svg
    - packages/auth_buttons/images/default/huawei_white.svg
    - packages/auth_buttons/images/default/microsoft.svg
    - packages/auth_buttons/images/default/twitter.svg
    - packages/auth_buttons/images/default/twitter_white.svg

    - packages/auth_buttons/images/outlined/apple.svg
    - packages/auth_buttons/images/outlined/apple_white.svg
    - packages/auth_buttons/images/outlined/email.svg
    - packages/auth_buttons/images/outlined/email_white.svg
    - packages/auth_buttons/images/outlined/facebook.svg
    - packages/auth_buttons/images/outlined/facebook_white.svg
    - packages/auth_buttons/images/outlined/github.svg
    - packages/auth_buttons/images/outlined/github_white.svg
    - packages/auth_buttons/images/outlined/google.svg
    - packages/auth_buttons/images/outlined/huawei.svg
    - packages/auth_buttons/images/outlined/huawei_white.svg
    - packages/auth_buttons/images/outlined/microsoft.svg
    - packages/auth_buttons/images/outlined/twitter.svg
    - packages/auth_buttons/images/outlined/twitter_white.svg

    - packages/auth_buttons/images/secondary/apple.svg
    - packages/auth_buttons/images/secondary/email.svg
    - packages/auth_buttons/images/secondary/facebook.svg
    - packages/auth_buttons/images/secondary/github.svg
    - packages/auth_buttons/images/secondary/google.svg
    - packages/auth_buttons/images/secondary/huawei.svg
    - packages/auth_buttons/images/secondary/microsoft.svg
    - packages/auth_buttons/images/secondary/twitter.svg
