name: auth_buttons
description: Auth Buttons is a flutter widget library, include buttons for authenticating with the most popular social networks like Google, Facebook, Apple and Twitter.
version: 0.0.6
homepage: https://github.com/elbeicktalat/flutter_auth_buttons

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - packages/auth_buttons/images/default/google.png
    - packages/auth_buttons/images/default/facebook.png
    - packages/auth_buttons/images/default/facebook_white.png
    - packages/auth_buttons/images/default/apple_black.png
    - packages/auth_buttons/images/default/apple_white.png
    - packages/auth_buttons/images/default/twitter.png
    - packages/auth_buttons/images/default/twitter_white.png
    - packages/auth_buttons/images/default/github_white.png
    - packages/auth_buttons/images/default/github_black.png
    - packages/auth_buttons/images/default/microsoft.png
    - packages/auth_buttons/images/default/email.png
    - packages/auth_buttons/images/default/email_white.png
    - packages/auth_buttons/images/default/huawei.png
    - packages/auth_buttons/images/default/huawei_white.png

    - packages/auth_buttons/images/outlined/google.png

    - packages/auth_buttons/images/secondary/google.png
