name: auth_buttons
description: Auth Buttons is a flutter widget library, include buttons for authenticating with the most popular social networks like Google, Facebook, Apple and Twitter.
version: 0.0.5
homepage: https://github.com/elbeicktalat/flutter_auth_buttons

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - packages/auth_buttons/images/google_logo.png
    - packages/auth_buttons/images/facebook_logo_white.png
    - packages/auth_buttons/images/apple_logo_black.png
    - packages/auth_buttons/images/apple_logo_white.png
    - packages/auth_buttons/images/twitter_logo.png
    - packages/auth_buttons/images/twitter_logo_white.png
    - packages/auth_buttons/images/github_logo.png
    - packages/auth_buttons/images/microsoft_logo.png
    - packages/auth_buttons/images/email_password_logo.png
